services:
  - type: web
    name: inventory_system
    env: python
    region: oregon

    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev pkg-config poppler-utils && \
      pip install --upgrade pip && \
      pip install -r requirements.txt

    startCommand: gunicorn ocr_project.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_system.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        sync: false  # Set manually on Render
      - key: DEBUG
        value: 'False'

    postDeploy:
      - python manage.py migrate
