# Generated by Django 5.2.1 on 2025-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='Unknown'),
        ),
    ]
