# Generated by Django 5.2.1 on 2025-06-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='inventory.inventoryitem'),
        ),
    ]
