# Generated by Django 5.2.1 on 2025-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_requestitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
