# Generated by Django 5.2.1 on 2025-07-04 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_requestitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestitem',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
