# Generated by Django 5.2.1 on 2025-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='description',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
